apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopcart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopcart-deployment
  template:
    metadata:
      labels:
        app: shopcart-deployment
    spec:
      containers:
      - name: shopcart-dev
        image: shopcart-dev
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: shopcart-dev-service
# spec:
#   selector:
#     app: shopcart-dev
#   type: LoadBalancer
#   ports:
#   - protocol: TCP
#     port: 3000
#     targetPort: 3000
#     nodePort: 30000
